apiVersion: v1
kind: Service
metadata:
  name: cryptogenweb-service
  labels:
    name: cryptogenweb-service
    app: cryptogenweb
spec:
  selector:
    name: cryptogenweb-service
  type: NodePort
  ports:
   - port: 80
     name: http
     targetPort: 5000
     protocol: TCP
