apiVersion: v1
kind: Service
metadata:
  name: crytogenweb-service
  labels:
    name: crytogenweb-service
    app: crytogenweb
spec:
  selector:
    name: crytogenweb-service
  type: NodePort
  ports:
   - port: 80
     name: http
     targetPort: 5000
     protocol: TCP
