apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
    app: crytogenweb
spec:
  ports:
  - port: 3306
    name: mysql
    targetPort: 3306
  selector:
    name: mysql
    app: crytogenweb
